plugins {
    id 'idea'
    id 'java'
    id 'net.minecraftforge.accesstransformers'
    id 'net.minecraftforge.gradle'
    id 'net.minecraftforge.jarjar'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

minecraft {
    accessTransformer = true
    mappings channel: 'parchment', version: "${parchment_version}-${parchment_minecraft}"
}

repositories {
    maven { name = 'Bawnorton'; url = 'https://maven.bawnorton.com/releases' }

    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven

    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")

    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixinextras_version}"))
    implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${mixinsquared_version}"))

    implementation "org.ow2.asm:asm:9.5"
    implementation "org.ow2.asm:asm-tree:9.5"

    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'

    implementation 'com.lmax:disruptor:3.4.4'
    implementation 'it.unimi.dsi:fastutil:8.5.12'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

idea.module { downloadJavadoc = downloadSources = true }
